### ISSUE TITLE
Side-by-side comparison missing

### ISSUE THREAD

**Issue by csbenz** [jenzz/Android-MaterialPreference#14]
In the readme you wanted to show a side-by-side comparison but the material screenshot is missing. Would be nice to have to be able to compare before using the lib. Thanks!

**Comment by jenzz** [comment]
You can see them side-by-side in that single screenshot.
They just look so identical you didn't even notice. :wink:

**Comment by csbenz** [comment]
Oh I see, I didn't understand that :) You should change the name from "screenshots" to "screenshot" so it's clearer. Thank you!
