### ISSUE TITLE
ListPreference MultiSelectListPreference

### ISSUE THREAD

**Issue by askfor** [jenzz/Android-MaterialPreference#5]
Would you add support for ListPreference and MultiSelectListPreference ?
Thanks

**Comment by jenzz** [comment]
Hi @askfor 

As I mentioned in the README, I'm currently using the [material-dialogs](https://github.com/afollestad/material-dialogs) library for any popup / dialog related preferences.
So I'm not planning to re-implement them, but feel free to send a pull request. :smiley:

**Comment by askfor** [comment]
Thanks, material-dialogs has MultiSelectListPreference  now :)

**Comment by daniele-athome** [comment]
About this same issue: I'm mixing preference classes from material-dialogs with yours, but they come out with different style (colors, margins). Is there a way to use the same theme from your library (which seems the most material-compliant)?
