### ISSUE TITLE
CheckBoxPreference disableDependentsState not working

### ISSUE THREAD

**Issue by msutherland4807** [jenzz/Android-MaterialPreference#6]
As in title, I have my disableDependentsState set to true, so that when my CheckBox is ticked, another pref is disabled, however no matter how I set the attribute, the other pref is always enabled/disabled when CheckBox on/off respectively

I've tried using the source lib and changing line 42 to look in index 2 (which I think is correct anyway) but it still doesn't seem to work

Thanks for the lib!

**Comment by msutherland4807** [comment]
Never mind, changing it to index 2 did work, my mistake.

If you could edit it in the lib that'd be awesome :)

**Comment by msutherland4807** [comment]
Have opened pull request instead

**Comment by jenzz** [comment]
Yep. That's a bug. Well spotted.

I will review and merge your PR soon and then do a simple patch release to Maven Central.
