### ISSUE TITLE
Switch Preference

### ISSUE THREAD

**Issue by slidenerd** [jenzz/Android-MaterialPreference#9]
![snap 2015-03-22 at 11 00 26](https://cloud.githubusercontent.com/assets/5139030/6768185/b7798470-d082-11e4-901c-5673ed6f7050.png)
I just found out there is no switch preference, should I use the one available in stock <SwitchPreference> or switch to something else? any advice? thanks for your reply in advance

**Comment by msutherland4807** [comment]
Not my library but I proposed pull request #8 to add the Switch Preference. You could either copy source from my fork or wait and see if @jenzz merges it in

**Comment by jenzz** [comment]
Yep. I was thinking about adding a `SwitchPreference` myself since it's a simple addition and a frequently used widget.

I'm gonna close this issue given @msutherland4807 has already created a PR (#8) for this.
I will merge and release it as part of v1.3.
